docs
epi-project/brane pull request #137
Opened 2024-10-04 09:39 UTC by DanielVoogsgerd

This should resolve all the warnings in the docs.
Furthermore, this should from now on disallow the introductions of warnings in CI

2024-10-08 10:06 UTC, Lut99 requested changes
Thanks! I hadn't thought about rustdoc warnings. I've left a few minor comments, though, for maximum matching my intensions :)

2024-10-08 10:06 UTC, Lut99 commented on brane-cli/src/errors.rs
> +    /// Failed to find a user directory. The `what` hints at the kind of user directory (fill in "`<WHAT>` directory", e.g., "config", "data", ...)
I guess I don't agree with clippy here xD the "what" is part of the string, shouldn't contain any backticks in it. If you like, I'd prefer then to have the whole string backtick'ed

(I'm expressing that <WHAT> is a placeholder in the string to be replaced with the examples "config", "data", etc)

2024-10-08 10:06 UTC, Lut99 commented on brane-cli/src/run.rs
> +/// - `what`: The thing we're running. Either a filename, or something like `<stdin>`.
Can also remove the `<` and `>` here

2024-10-08 10:06 UTC, Lut99 commented on brane-ctl/src/errors.rs
> +    /// The `what` should fill in the `<WHAT>` in: "Cannot `<WHAT>` on a ... node"
Same as above; the quote doesn't include backticks. Quote the entire string?

2024-10-08 10:06 UTC, Lut99 commented on brane-exe/src/pc.rs
> +    /// This function returns a new instance. To update an existing one, use [`ProgramCounter::jump_mut()`].
OK yeah thanks, I've been wildly inconsistent in this. I'll use that from now on xD

2024-10-08 10:18 UTC, DanielVoogsgerd commented on brane-cli/src/errors.rs
> +    /// Failed to find a user directory. The `what` hints at the kind of user directory (fill in "`<WHAT>` directory", e.g., "config", "data", ...)
The main problem is that it was trying to render the `<WHAT>` as HTML. Putting it in backticks works around that issue, but I think I can also just escape the `<` and `>`. I will try that.

2024-10-13 11:29 UTC, DanielVoogsgerd commented
Comments should be resolved.

2024-10-14 09:15 UTC, Lut99 commented
They are. Want to rebase #163 first?

2024-10-15 11:57 UTC, Lut99 approved these changes

2024-10-15 11:57 UTC, merged